RecipeBox/Models/Recipe.cs
using System.Collections.Generic;

namespace RecipeBox.Models
{
  public class Recipe
  {
    public Recipe()
    {
      this.JoinEntities = new HashSet<RecipeTag>();
    }

    public int RecipeId { get; set; }
    public string Title { get; set; }
    public string Instructions { get; set; }
    public string Ingredients { get; set;}
    public string Rating { get; set; }
    public int Time { get; set; }
    public virtual ApplicationUser User { get; set; }
    public virtual ICollection<RecipeTag> JoinEntities { get; set; }
  }
}

RecipeBox/Controllers/RecipesController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using RecipeBox.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace RecipeBox.Models
{
  [Authorize]
  public class RecipesController : Controller
  {
    private readonly RecipeBoxContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public RecipesController(UserManager<ApplicationUser> userManager, RecipeBoxContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    public async Task<ActionResult> Index()
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      var userItems = _db.Recipes.Where(entry => entry.User.Id == currentUser.Id).OrderByDescending(model => model.Rating).ToList();
      return View(userItems);
    }

    public async Task<ActionResult> Create()
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      var userTags = _db.Tags.Where(entry => entry.User.Id == currentUser.Id);
      ViewBag.TagId = new SelectList(userTags, "TagId", "TagName");
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Recipe recipe, int TagId)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      recipe.User = currentUser;
      _db.Recipes.Add(recipe);
      _db.SaveChanges();
      if (TagId != 0)
      {
        _db.RecipeTag.Add(new RecipeTag() { TagId = TagId, RecipeId = recipe.RecipeId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisRecipe = _db.Recipes
        .Include(recipe => recipe.JoinEntities)
        .ThenInclude(join => join.Tag)
        .FirstOrDefault(recipe => recipe.RecipeId == id);
      return View(thisRecipe);
    }

    public async Task<ActionResult> Edit(int id)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      var userTags = _db.Tags.Where(entry => entry.User.Id == currentUser.Id);
      var thisRecipe = _db.Recipes.FirstOrDefault(recipe => recipe.RecipeId == id);
      ViewBag.TagId = new SelectList(userTags, "TagId", "TagName");
      return View(thisRecipe);
    }

    [HttpPost]
    public ActionResult Edit(Recipe recipe, int TagId)
    {
      if (TagId != 0)
      {
        _db.RecipeTag.Add(new RecipeTag() { TagId = TagId, RecipeId = recipe.RecipeId });
      }
      _db.Entry(recipe).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public async Task<ActionResult> AddTag(int id)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      var userTags = _db.Tags.Where(entry => entry.User.Id == currentUser.Id);
      var thisRecipe = _db.Recipes.FirstOrDefault(recipe => recipe.RecipeId == id);
      ViewBag.TagId = new SelectList(userTags, "TagId", "TagName");
      return View(thisRecipe);
    }

    [HttpPost]
    public ActionResult AddTag(Recipe recipe, int TagId)
    {
      if (TagId != 0 && !_db.RecipeTag.Any(model => model.RecipeId == recipe.RecipeId && model.TagId == TagId))
      {
        _db.RecipeTag.Add(new RecipeTag() { TagId = TagId, RecipeId = recipe.RecipeId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisRecipe = _db.Recipes.FirstOrDefault(recipe => recipe.RecipeId == id);
      return View(thisRecipe);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisRecipe = _db.Recipes.FirstOrDefault(recipe => recipe.RecipeId == id);
      _db.Recipes.Remove(thisRecipe);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteTag(int joinId)
    {
      var joinEntry = _db.RecipeTag.FirstOrDefault(entry => entry.RecipeTagId == joinId);
      _db.RecipeTag.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Search()
    {
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Search(string Ingredients)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      string searchName = Ingredients.ToLower();
      List<Recipe> currentUserRecipes = _db.Recipes.Where(entry => entry.User.Id == currentUser.Id).ToList();
      List<Recipe> searchResults = currentUserRecipes.Where(recipe => recipe.Ingredients.ToLower().Contains(searchName)).ToList();
      return View("Index", searchResults);
    }
  }
}

RecipeBox/Views/Recipes/AddTag.cshtml
@{
  Layout = "_Layout";
}

@model RecipeBox.Models.Recipe

<h3>Add a Tag to this Recipe: @Html.DisplayFor(model => model.Title)</h3>
<hr>

@using (Html.BeginForm())
{
  <div class="form-group">
    @Html.HiddenFor(model => model.RecipeId)

    <h4>@Html.Label("Select Tag")</h4>
    @Html.DropDownList("TagId", null, new { @class = "form-control"})
    <br>
    <input type="submit" value="Save" class = "btn btn-light ButtonText"/>
  </div>
}

<p class = "btn btn-light">@Html.ActionLink("Back to list", "Index", null, null, new {@class = "ButtonText"})</p>

RecipeBox/Views/Recipes/Create.cshtml
@{
  Layout = "_Layout";
}

@model RecipeBox.Models.Recipe

<h3>Add a New Recipe:</h3>
<hr>

@using (Html.BeginForm())
{
  <h4>@Html.LabelFor(model => model.Title)</h4>
  @Html.TextBoxFor(model=> model.Title, new { @class = "form-control", @required = "required" })
  <br>
  <h4>@Html.LabelFor(model => model.Instructions)</h4>
  @Html.TextAreaFor(model=> model.Instructions, new { @class = "form-control form-control-full", rows = 5 })
  <br>
  <h4>@Html.LabelFor(model => model.Ingredients)</h4>
  @Html.TextAreaFor(model=> model.Ingredients, new { @class = "form-control form-control-full", rows = 5 })
  <br>
  <h4>Total @Html.LabelFor(model => model.Time) in Minutes</h4>
  @Html.TextBoxFor(model => model.Time, new { @class = "form-control", @type = "number"})
  <br>
  <h4>@Html.LabelFor(model => model.Rating)</h4>
  @Html.DropDownList("Rating", new List<SelectListItem> {
    new SelectListItem { Text= "⭐", Value = "⭐" },
    new SelectListItem { Text= "⭐⭐", Value = "⭐⭐" },
    new SelectListItem { Text= "⭐⭐⭐", Value = "⭐⭐⭐" },
    new SelectListItem { Text= "⭐⭐⭐⭐", Value = "⭐⭐⭐⭐" },
    new SelectListItem { Text= "⭐⭐⭐⭐⭐", Value = "⭐⭐⭐⭐⭐" }
  }, new { @class = "form-control"})
  <br>
  <input type="submit" value="Add New Recipe" class="btn btn-light ButtonText"/>
}

<br>
<p class="btn btn-light">@Html.ActionLink("Show All Recipes", "Index", null, null, new { @class = "ButtonText" })</p>

RecipeBox/Views/Recipes/Delete.cshtml
@{
  Layout = "_Layout";
}

@model RecipeBox.Models.Recipe

<h4>Are you sure you want to delete this?</h4>

<br>
<p>Recipe Title: @Html.DisplayFor(model => model.Title)</p>

@using (Html.BeginForm())
{
  <br>
  <input type="submit" value="Delete" class="btn btn-light ButtonText"/>
}

<br>
<p class="btn btn-light">@Html.ActionLink("Back to Recipes", "Index", null, null, new { @class = "ButtonText"})</p>

RecipeBox/Views/Recipes/Details.cshtml
@{
  Layout = "_Layout";
}

@model RecipeBox.Models.Recipe

<h3>@Model.Title</h3>
<hr>

<h4>Rating: @Model.Rating</h4>
<h5><em>Total Time: @Model.Time minutes</em></h5>

<h3>Ingredients</h3>
<p class="paragraph">@Model.Ingredients</p>

<h3>Instructions</h3>
<p class="paragraph">@Model.Instructions</p>

@if(@Model.JoinEntities.Count == 0)
{
  <p>This recipe has no tags.</p>
}
else
{
  <h3>Tags:</h3>

    @foreach(var join in Model.JoinEntities)
    {
      <div class = "card-deck">
        <div class="card text-center mb-3" style="width: 24rem;">
          <div class="card-body">
            <h5 class="card-title" style="color:black;">@join.Tag.TagName</h5>
            @using (Html.BeginForm("DeleteTag", "Recipes"))
            {
              @Html.Hidden("joinId", @join.RecipeTagId)
              <input type="submit" value="Delete" class="btn btn-light ButtonText"/>
            }
          </div>
        </div>
      </div>
    }
}

<p class="btn btn-light">@Html.ActionLink("Edit this Recipe", "Edit", new { id = Model.RecipeId }, new { @class = "ButtonText" })</p>
<p class="btn btn-light">@Html.ActionLink("Delete this Recipe", "Delete", new { id = Model.RecipeId}, new { @class = "ButtonText"})</p>
<p class="btn btn-light">@Html.ActionLink("Add a Tag to this Recipe", "AddTag", new {id = Model.RecipeId}, new { @class = "ButtonText"})</p>

RecipeBox/Views/Recipes/Edit.cshtml
@{
  Layout = "_Layout";
}

@model RecipeBox.Models.Recipe

<h2>Edit</h2>

<h3>Edit this recipe: @Model.Title</h3>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.RecipeId)

  @Html.LabelFor(model => model.Title)
  @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", @required = "required" } })

  @Html.LabelFor(model => model.Ingredients)
  @Html.EditorFor(model => model.Ingredients, new { htmlAttributes = new { @class = "form-control" } })

  @Html.LabelFor(model => model.Instructions)
  @Html.EditorFor(model => model.Instructions, new { htmlAttributes = new { @class = "form-control"} })

  @Html.Label("Total Time in Minutes")
  @Html.EditorFor(model => model.Time, new { htmlAttributes = new { @class = "form-control" } })

  @Html.LabelFor(model => model.Rating)
  @Html.EditorFor(model => model.Rating, new { htmlAttributes = new { @class = "form-control"} })

  <input type="submit" value="Save" class="btn btn-light ButtonText"/>


}

RecipeBox/Views/Recipes/Index.cshtml
@{
  Layout = "_Layout";
}

@using RecipeBox.Models
@model IEnumerable<RecipeBox.Models.Recipe>

<h3>@User.Identity.Name's Recipes</h3>

@if (Model.Any())
{
  @foreach (Recipe recipe in Model)
  {
    <div class = "card-deck">
      <div class="card text-center mb-3" style="width: 24rem;">
        <div class="card-body">
        <h5 class="card-title">@Html.ActionLink($"{recipe.Title}", "Details", new { id = recipe.RecipeId})</h5>
          <p class="card-text" style="color:grey;">Total Time: @recipe.Time minutes</p>
            <div class="card-footer text-muted">
              Your Rating: @recipe.Rating
          </div>
        </div>
      </div>
    </div>
  }
}
else
{
  <p>You have no recipes yet.</p>
}

<p class="btn btn-light">@Html.ActionLink("Add a Recipe", "Create", null, null, new { @class="ButtonText"})</p>
<p class="btn btn-light">@Html.ActionLink("Search Recipes", "Search", null, null, new { @class = "ButtonText"})</p>

RecipeBox/Views/Recipes/Search.cshtml
@{
  Layout = "_Layout";
}

@model RecipeBox.Models.Recipe
@using RecipeBox.Models

<h3>Search Recipes by Ingredients</h3>

@using (Html.BeginForm())
{
  @Html.TextBoxFor(model => model.Ingredients, null, new { @class = "form-control"})
  <br>
  <input type="submit" value="Search" class="btn btn-light ButtonText"/>
}